"""QA-facing pytest terminal report for generated API tests."""

import os
from pprint import pformat


def _generated_api_tests():
    os.environ.setdefault("MCP_DISABLE_IMPORT", "1")
    os.environ.setdefault("JIRA_MODE", "mock")
    os.environ.setdefault("TEST_GENERATION_MODE", "rule")
    os.environ.setdefault("APP_BASE_URL", "https://restful-booker.herokuapp.com")

    from src import server

    ticket_keys = ["RB-1", "RB-2", "RB-3", "RB-4", "RB-5"]
    evidence = []
    for key in ticket_keys:
        ticket = server.fetch_jira_ticket(key)
        tests = server.generate_api_test_cases(ticket)
        evidence.append((ticket, tests))
    return evidence


def pytest_terminal_summary(terminalreporter, exitstatus, config):
    """Print the QA-facing generated test evidence."""
    terminalreporter.section("QA Report - Restful Booker Jira Tickets and Generated API Tests")

    for ticket, generated_tests in _generated_api_tests():
        terminalreporter.write_line(f"Source ticket: {ticket['key']} - {ticket['summary']}")
        terminalreporter.write_line(f"Acceptance criteria: {ticket['acceptance_criteria']}")
        for index, test in enumerate(generated_tests, start=1):
            terminalreporter.write_line(f"  Generated API Test {index}: {test['name']}")
            terminalreporter.write_line(f"    Generated by: {test.get('source', 'unknown')}")
            terminalreporter.write_line(f"    Traceability: {test.get('traceability', '')}")
            terminalreporter.write_line(f"    Method: {test['method']}")
            terminalreporter.write_line(f"    Endpoint: {test['endpoint']}")
            if test.get("setup_steps"):
                terminalreporter.write_line("    Setup steps:")
                for step in test["setup_steps"]:
                    terminalreporter.write_line(f"      - {step['method']} {step['endpoint']} extract={step.get('extract', {})}")
            if test.get("follow_up_steps"):
                terminalreporter.write_line("    Follow-up checks:")
                for step in test["follow_up_steps"]:
                    terminalreporter.write_line(f"      - {step['method']} {step['endpoint']} expect={step.get('expected_status')}")
            terminalreporter.write_line(f"    Headers: {pformat(test.get('headers', {}))}")
            terminalreporter.write_line(f"    Body: {pformat(test.get('body', {}))}")
            terminalreporter.write_line(f"    Expected status: {test['expected_status']}")
            terminalreporter.write_line(f"    Expected response fields: {test.get('expected_field_paths') or test.get('expected_fields', [])}")
        terminalreporter.write_line("")

    terminalreporter.section("QA Report - What was executed")
    terminalreporter.write_line("1. Restful Booker mock Jira tickets map to real public API endpoints.")
    terminalreporter.write_line("2. Generated tests include executable setup steps for stateful workflows.")
    terminalreporter.write_line("3. The runner extracts runtime values such as bookingid and token.")
    terminalreporter.write_line("4. The runner validates status codes, response field paths, and follow-up checks.")
